project:
  type: website
  output-dir: docs
website:
  title: "erikringen.github.io"
  site-url: https://erikringen.github.io
  repo-url: https://github.com/ErikRingen/erikringen.github.io
  repo-actions: [edit, issue]
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ErikRingen
      - icon: twitter
        href: https://x.com/err_ring
format:
  html:
    theme: minty
    css: styles.css
execute:
  freeze: auto



